# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.7.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end
  
  desc "Add new device to provisioning profile"
  lane :add_device do
        device_name = prompt(text: "Enter the device name: ")
        device_udid = prompt(text: "Enter the device UDID: ")
        device_hash = {}
        device_hash[device_name] = device_udid
        register_devices(
          devices: device_hash
        )
      refresh_profiles
    end

    # A helper lane for refreshing provisioning profiles.
    lane :refresh_profiles do
      match(
        force_for_new_devices: true,
        app_identifier:"net.mcmains.things"
     )
     match(
       force_for_new_devices: true,
       app_identifier:"net.mcmains.things.things-Today"
    )
    end
  
  
  desc "Grab provisioning profiles"
  lane :profiles do
    match(app_identifier:"net.mcmains.things")
    match(app_identifier:"net.mcmains.things.things-Today")
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(app_identifier:"net.mcmains.things", type: "appstore")
    match(app_identifier:"net.mcmains.things.things-Today", type: "appstore")
    
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "3things")
    upload_to_app_store                  # upload your app to App Store Connect
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
